import { execSync } from "node:child_process";
import { readdirSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const SRC = "public/photography";
const TMP = ".photo-tmp";
const MAX_EDGE = 1400;

// Existing processed outputs — never treat these as inputs or delete them.
const PROCESSED_RE = /^photo-\d+\.webp$/i;

// New inputs: image files that are NOT already processed outputs.
const newFiles = readdirSync(SRC)
  .filter((f) => /\.(heic|jpg|jpeg|webp|png)$/i.test(f) && !PROCESSED_RE.test(f))
  .sort((a, b) => parseInt(b, 10) - parseInt(a, 10)); // numeric prefix desc = newest first

if (newFiles.length === 0) {
  console.log("No new photos to process.");
  process.exit(0);
}

// Determine the highest existing photo-NN number so new photos continue the sequence.
const existingNums = readdirSync(SRC)
  .filter((f) => PROCESSED_RE.test(f))
  .map((f) => parseInt(f.replace(/^photo-0*/, "").replace(/\.webp$/i, ""), 10))
  .filter((n) => !isNaN(n));
const maxExisting = existingNums.length > 0 ? Math.max(...existingNums) : 0;

mkdirSync(TMP, { recursive: true });

try {
  const newManifestEntries = [];

  // Process each new input, assigning numbers after the existing max.
  for (let i = 0; i < newFiles.length; i++) {
    const input = path.join(SRC, newFiles[i]);
    const num = maxExisting + i + 1;
    const outName = `photo-${String(num).padStart(2, "0")}.webp`;
    const outPath = path.join(SRC, outName);

    let readable = input;
    if (/\.heic$/i.test(input)) {
      readable = path.join(TMP, `${i}.png`);
      execSync(`sips -s format png "${input}" --out "${readable}"`, { stdio: "pipe" });
    }

    const img = sharp(readable).rotate();
    const meta = await img.metadata();

    if (!meta.width || !meta.height) throw new Error(`Cannot read dimensions: ${input}`);

    const scale = Math.min(1, MAX_EDGE / Math.max(meta.width, meta.height));
    const width = Math.round(meta.width * scale);
    const height = Math.round(meta.height * scale);

    // effort: 6 is intentional — max compression for one-off batch encodes.
    await sharp(readable).rotate().resize(width, height).webp({ quality: 75, effort: 6 }).toFile(outPath);

    const blur = await sharp(outPath).resize(12).webp({ quality: 30 }).toBuffer();
    newManifestEntries.push({
      src: `/photography/${outName}`,
      width,
      height,
      blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
    });
    console.log(`${newFiles[i]} -> ${outName} (${width}x${height})`);
  }

  // Regenerate manifest entries for all existing photo-NN files, ordered by NN ascending
  // (preserves the original newest-first display order since lower numbers = newer photos).
  const existingFiles = readdirSync(SRC)
    .filter((f) => PROCESSED_RE.test(f))
    .filter((f) => {
      const num = parseInt(f.replace(/^photo-0*/, "").replace(/\.webp$/i, ""), 10);
      return num <= maxExisting;
    })
    .sort((a, b) => {
      const na = parseInt(a.replace(/^photo-0*/, "").replace(/\.webp$/i, ""), 10);
      const nb = parseInt(b.replace(/^photo-0*/, "").replace(/\.webp$/i, ""), 10);
      return na - nb;
    });

  const existingManifestEntries = [];
  for (const f of existingFiles) {
    const filePath = path.join(SRC, f);
    const img = sharp(filePath);
    const meta = await img.metadata();

    if (!meta.width || !meta.height) throw new Error(`Cannot read dimensions: ${filePath}`);

    const blur = await sharp(filePath).resize(12).webp({ quality: 30 }).toBuffer();
    existingManifestEntries.push({
      src: `/photography/${f}`,
      width: meta.width,
      height: meta.height,
      blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
    });
  }

  // New entries prepended before existing entries (newest-first display order).
  const manifest = [...newManifestEntries, ...existingManifestEntries];

  // Delete source originals after successful processing.
  for (const f of newFiles) rmSync(path.join(SRC, f));

  const ts = `// GENERATED by scripts/process-photos.mjs — do not edit by hand.
export interface Photo {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
}

export const photos: Photo[] = ${JSON.stringify(manifest, null, 2)};
`;
  writeFileSync("src/data/photos.ts", ts);
  console.log(`Wrote src/data/photos.ts with ${manifest.length} photos`);
} finally {
  rmSync(TMP, { recursive: true, force: true });
}
