import { execSync } from "node:child_process";
import { readdirSync, writeFileSync, mkdirSync, rmSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const SRC = "public/photography";
const TMP = ".photo-tmp";
const MAX_EDGE = 1400;

const files = readdirSync(SRC)
  .filter((f) => /\.(heic|jpg|jpeg|webp|png)$/i.test(f))
  .sort((a, b) => parseInt(b, 10) - parseInt(a, 10)); // numeric prefix desc = newest first

mkdirSync(TMP, { recursive: true });
const manifest = [];

for (let i = 0; i < files.length; i++) {
  const input = path.join(SRC, files[i]);
  const outName = `photo-${String(i + 1).padStart(2, "0")}.webp`;
  const outPath = path.join(SRC, outName);

  let readable = input;
  if (/\.heic$/i.test(input)) {
    readable = path.join(TMP, `${i}.png`);
    execSync(`sips -s format png "${input}" --out "${readable}"`, { stdio: "pipe" });
  }

  const img = sharp(readable).rotate();
  const meta = await img.metadata();
  const scale = Math.min(1, MAX_EDGE / Math.max(meta.width, meta.height));
  const width = Math.round(meta.width * scale);
  const height = Math.round(meta.height * scale);

  await sharp(readable).rotate().resize(width, height).webp({ quality: 64, effort: 6 }).toFile(outPath);

  const blur = await sharp(readable).rotate().resize(12).webp({ quality: 30 }).toBuffer();
  manifest.push({
    src: `/photography/${outName}`,
    width,
    height,
    blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
  });
  console.log(`${files[i]} -> ${outName} (${width}x${height})`);
}

for (const f of files) rmSync(path.join(SRC, f));
rmSync(TMP, { recursive: true, force: true });

const ts = `// GENERATED by scripts/process-photos.mjs — do not edit by hand.
export interface Photo {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
}

export const photos: Photo[] = ${JSON.stringify(manifest, null, 2)};
`;
writeFileSync("src/data/photos.ts", ts);
console.log(`Wrote src/data/photos.ts with ${manifest.length} photos`);
