// GENERATED by scripts/process-photos.mjs — do not edit by hand.
export interface Photo {
  src: string;
  width: number;
  height: number;
  blurDataURL: string;
}

export const photos: Photo[] = [
  {
    "src": "/photography/photo-01.webp",
    "width": 640,
    "height": 853,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoMABAABABoJaQAAxamQZVkPEiwAP7xc5WlDWrXWFCMs8jrnYw2tiT2wnjUGYvqgR8wVNndgr8NyXdDU6kUfhJZGAA="
  },
  {
    "src": "/photography/photo-02.webp",
    "width": 640,
    "height": 640,
    "blurDataURL": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoMAAwABABoJYwAAtz9GBEYAAD+72GQozKVlC9uo2adVZ1ia2kO6mBslwHwLBya+W2GHjpHc32PJSAA"
  },
  {
    "src": "/photography/photo-03.webp",
    "width": 640,
    "height": 853,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAADwAQCdASoMABAABABoJQBOgBwuK3KYXAAA159s3PoYFs+5Zkdr2snCuzXryZedp6sLlm3vhd5G9q0B2bastkrXKdjAAA=="
  },
  {
    "src": "/photography/photo-04.webp",
    "width": 640,
    "height": 640,
    "blurDataURL": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAAAQAgCdASoMAAwABABoJQBOgMXhiuY4WSMAAPQCddnwwJISM+Ljp5FiUraRcMkPCyiIeiDSmiinQcq/ALkYE/oOvdUmc/EPI3hxFfSjRpg6ZzIA"
  },
  {
    "src": "/photography/photo-05.webp",
    "width": 640,
    "height": 640,
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoMAAwABABoJYwEGAXEAroAAP7yO5Yd24ntISBaKdVYv56qytyeSiGDAAA="
  },
  {
    "src": "/photography/photo-06.webp",
    "width": 640,
    "height": 640,
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAQAgCdASoMAAwABABoJZACsAEVz9s422XwAP7xVMSkm952vZJg9QhVJvIfV8DLJPnCQd1094relJlqYAAAAA=="
  },
  {
    "src": "/photography/photo-07.webp",
    "width": 640,
    "height": 640,
    "blurDataURL": "data:image/webp;base64,UklGRmAAAABXRUJQVlA4IFQAAADQAQCdASoMAAwABABoJaQAAlhTSqMcnAD+yiA766wzTamLry9iH8FxoGqkqzZI0nBG5nLmIkL1ZTyN+vuv5h211d1drRZc0I0N272m3EjQ+xGQAAA="
  },
  {
    "src": "/photography/photo-08.webp",
    "width": 640,
    "height": 640,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoMAAwABABoJZwAAlvLeIAAAP718Lx+Ul96l2EOoghKRnGCIORH51IGvRkRwfnGMBVjsAAA"
  },
  {
    "src": "/photography/photo-09.webp",
    "width": 640,
    "height": 640,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoMAAwABABoJbACdADPvYl7xgAA+ez0H8Hr75sBIZAtTv3PvkZN99DcVbYfi267aJjTMve2l8WWRFaBEIv2AwnKFfcvkc7c7QAAAA=="
  },
  {
    "src": "/photography/photo-10.webp",
    "width": 640,
    "height": 480,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoMAAkABABoJbAC7AE2UpsXpMZAAP7BfSxHDk755HNlHEhUFPJlvryBz8yI1ebrGD4n6a1J0MKMgtGCMAAAAA=="
  },
  {
    "src": "/photography/photo-11.webp",
    "width": 640,
    "height": 640,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoMAAwABABoJbACw7Cgt+9AAAD+431SOHhpsBnOuijK0ykgH2ifYpW69rOsfPPKwwvRV9p7FkeaVrQOQAA="
  },
  {
    "src": "/photography/photo-12.webp",
    "width": 640,
    "height": 640,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoMAAwABABoJbACdDBKwXLm7xdxAAD+nwjslHS1kzTPtEPhCkQK89Fq6v5jhJmP3YzWQvmD0FPNXpixRl2mr9P9qP3/eD5bwOR5cd+rLHhYfnJvmp008AAA"
  },
  {
    "src": "/photography/photo-13.webp",
    "width": 640,
    "height": 640,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAAAwAgCdASoMAAwABABoJbACdAELXD4TlSqCAAD+eL50oxJ2L+/t+xnwHXz+K7hSnM0xOzLgVq7SnIILDKQMQj0FFERqDj8YSmQnn7HxgAA="
  },
  {
    "src": "/photography/photo-14.webp",
    "width": 1120,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoMAA8ABABoJaQAAxPobh/zwAD4wpz1Csxk4f8AjyA9PB6hyoWprTiETgAAAA=="
  },
  {
    "src": "/photography/photo-15.webp",
    "width": 1120,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAAAQAgCdASoMAA8ABABoJZQCdADJ8YH0gfYAAPjksLuXecnv4v8qwB0ncqb+/gAafwlLsmm5WYd7XPfpmyur54oBANStqQixJdHEhF9SMXG47EbSu+NAAA=="
  },
  {
    "src": "/photography/photo-16.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAABwAQCdASoMAAwABABoJZgCdABSgAD9IboQdnRa0y8RSa4ubIihs1827AAAAA=="
  },
  {
    "src": "/photography/photo-17.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADQAQCdASoMAAwABABoJaQAAp/O6D6iQAD+4YyANaJ+d8As+DMs9tPwFS4qFTC4AAAAAA=="
  },
  {
    "src": "/photography/photo-18.webp",
    "width": 1120,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRmYAAABXRUJQVlA4IFoAAAAwAgCdASoMAA8ABABoJYgCdAELY1aWzBtgAAD+9Xru4bI8WuXsG914HHrkUcw8OzXofUa9s0++HNSaEHo3DDrTp9nRcbKivwuX8y89DgLOFviILW6WjenAAAA="
  },
  {
    "src": "/photography/photo-19.webp",
    "width": 1120,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoMAA8ABABoJbACdAEQZ419gAD+wbwE2eQNE9uI8c2KGAJ1eyLYaxwgDFtzhx73vE/B7BE6KstzfwW9sBWhtBgAAAA="
  },
  {
    "src": "/photography/photo-20.webp",
    "width": 1400,
    "height": 1121,
    "blurDataURL": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAABQAgCdASoMAAoABABoJbACdGuAt/8DaaYgwAAA/vbhYhZ+0REc574e5Y1v//VqpfFlcga4Wq+dIh7DWXpmf484O+ESafzp6tc0U1L5TaknzwIBQ5WWAAAA"
  },
  {
    "src": "/photography/photo-21.webp",
    "width": 1120,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQAgCdASoMAA8ABABoJbACdDiAATtQuRYAAPgpfWo+aWbAxidU8fWfn53m8zptkyuMjE7W75nQEqOmvio+JHBE4XGVUXbHfR1DAoGc0alE3fdov1+LpiJ/ekxacs/eltp5Vm6K6/NC2FjnumPpGL1TmsZPC6//p7UAAA=="
  },
  {
    "src": "/photography/photo-22.webp",
    "width": 1119,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRk4AAABXRUJQVlA4IEIAAADQAQCdASoMAA8ABABoJaQAAloxW/Fs4AD+TKuPzNnhioR/kCU6MDBixkz4lDDsdM8WPSVtIjcwJfwy8tkK0PmAAAA="
  },
  {
    "src": "/photography/photo-23.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAACwAQCdASoMAAwABABoJaQAAtzrEe7AAP72r5qNdp5q6j3aYLsFDJaDf3/V7lAAAAA="
  },
  {
    "src": "/photography/photo-24.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAABQAgCdASoMAAwABABoJbACdAEUpUx1lZLwVAAA/tj5Rfh3VReVgPBDmTGWE5ZOt9t5vFCcf6M+aHfY/X2RsrvWvPzYkAAA"
  },
  {
    "src": "/photography/photo-25.webp",
    "width": 1120,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAAAQAgCdASoMAA8ABABoJaQAD5JtYiZTxmAAAPa/Z1Tb5Me7bhxd6kbu9RgIDVaqwix2E8tF3q/uZWxLX+sPhHc5UKmnSfvsnVPkd4vg1vcMXW4ACUZPFCWypa+n2/ayPAZgAA=="
  },
  {
    "src": "/photography/photo-26.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADwAQCdASoMAAwABABoJaQAAmifJgsN6AAAzja+p+Od1w6xnN6t5jWIfTiMnKxkgyth9LbQoWSylzcrPcyH1ZSZBeURWbb/8s4LsuXe/VToZ+K4HMAAAA=="
  },
  {
    "src": "/photography/photo-27.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAQAgCdASoMAAwABABoJbACdADhmgaoRdV2APyqf2lCeR5OaeLJU2NXIJQrrvZIhKO9u5gjpbBgCBh17gP0w93DCzQjBqvZ3ncL0V+55sGEvfXr2/mVd3YBbO/2YAAA"
  },
  {
    "src": "/photography/photo-28.webp",
    "width": 1400,
    "height": 1120,
    "blurDataURL": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADwAQCdASoMAAoABABoJbACdAEOz8usO7AA/ubSQgrlpBq8w6batvXpLJmMhzoAL3J/JX79hKVUi6kIrAXVkLp6yiiG2NTfVpMtdgl92HgAAA=="
  },
  {
    "src": "/photography/photo-29.webp",
    "width": 1121,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAADQAQCdASoMAA8ABABoJZwAAvqxKlIkwAD+X+SHCWRcNRTrnlDuq/TahejA7pNh5yo9n/XjePXT3HAAAAA="
  },
  {
    "src": "/photography/photo-30.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoMAAwABABoJZwAAuTUIuQAAP55PmUzLte0WibV80euvfzkpZ0HreIG8fk3mHwtC1qTw1FgQAA="
  },
  {
    "src": "/photography/photo-31.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoMAAwABABoJaQAAiFkdXSkAAD+p7RQEOOVO4rVdgJ9/UiQmzD1zr7GK4aYAAAA"
  },
  {
    "src": "/photography/photo-32.webp",
    "width": 1120,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAAAwAQCdASoMAA8ABABoJZQAA3AA/vLBiVg79PaAeOfqfxBynz16ylFmkltiAAAA"
  },
  {
    "src": "/photography/photo-33.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAQAgCdASoMAAwABABoJYgCdAEf//LIz7AAAP5z5HW/1bofYHaASeTnlmeOQcBj+GuAXxlAAAA="
  },
  {
    "src": "/photography/photo-34.webp",
    "width": 1400,
    "height": 1109,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoMAAoABABoJaQAAu0qTYwAAP6fRCe7M0P4r3fsWFkXNF+qN7791aRQgs28bBhi7ezP5xNgAAA="
  },
  {
    "src": "/photography/photo-35.webp",
    "width": 1120,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoMAA8ABABoJaQAAl1QL04IAAD+za19AWE+1wW3Kz4ET+g6cIpr0MFitY9NyB9fOWxw+LiLJnod5Lt5+FWSZBOiSWiXPEsYAAA="
  },
  {
    "src": "/photography/photo-36.webp",
    "width": 1120,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAQAgCdASoMAA8ABABoJbACdADdk/hjcI7AAP7CBluH89aeFozsfzgf81rUP7a33f1a2BHS39cuVs+v5wi3NUxxwZarXAAA"
  },
  {
    "src": "/photography/photo-37.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADQAQCdASoMAAwABABoJaQAAp1dlJ4kAAD+9hF6cJ+UdbtFOnR9SpzT/O30Sqlx4MOi4AAA"
  },
  {
    "src": "/photography/photo-38.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRlAAAABXRUJQVlA4IEQAAAAQAgCdASoMAAwABABoJaQAAxcChYOLfHgAAOJtSFLGOJu6R3bGM4MZnRSOxWReergs+BOHrFIav/JbJGQDzOhLUAAAAA=="
  },
  {
    "src": "/photography/photo-39.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAABwAQCdASoMAAwABABoJaQAAfIXAADNvRUUamB7T9w62AkDFD5d0XWjRd+o2z0eA3VAAA=="
  },
  {
    "src": "/photography/photo-40.webp",
    "width": 1400,
    "height": 1050,
    "blurDataURL": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAADwAQCdASoMAAkABABoJaQAAsSOgBelEAAA/u0JssopcyO9Y2sKVIkgHkPCIK/8xBMGq+YuAqhNegTbzJcRk8gglM/TukZWvbyAAA=="
  },
  {
    "src": "/photography/photo-41.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAAAQAgCdASoMAAwABABoJYwC7AD7jx5iz7cAAP7syJO30M9wXPmdi7f4ebv5OUCOxweVIhJZpiEgyf+OQGqVdX2xBXoGhuVYAAA="
  },
  {
    "src": "/photography/photo-42.webp",
    "width": 1400,
    "height": 1051,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAwAgCdASoMAAkABABoJYgCdEf/gY0KjLEEiADKQGvU3cugmsfBlaWWQqBJNMKY5rP9CihRmLZDEFD/+w/TfKbRGNNoRGAA"
  },
  {
    "src": "/photography/photo-43.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAACwAQCdASoMAAwABABoJZQAAlxULTfQAP73glbOR6SQ+BycgyOuZjhwQ/nn6eluvJHK8BfoTYAAAA=="
  },
  {
    "src": "/photography/photo-44.webp",
    "width": 1400,
    "height": 788,
    "blurDataURL": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAACwAQCdASoMAAcABABoJQAASuzvB2ogAP6G+W8r4jvlB478bjkvnRkoL2cch+wdu7MOAQbv+Xli2gHhZHQAAA=="
  },
  {
    "src": "/photography/photo-45.webp",
    "width": 719,
    "height": 719,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADwAQCdASoMAAwABABoJYgC7ADdoOg1f0AA/uqRzh65PmMk6Rc7hn/jxBe4WvWsMpGn3ePj3ufddLd2nubcFQwIpafFbgAA"
  },
  {
    "src": "/photography/photo-46.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAACwAQCdASoMAAwABABoJZgCdACA4xRMAP67+EcD4hy3vfvXhU1SV1bVmB4vHpkp7MDroJ40l/GEx9eAAAA="
  },
  {
    "src": "/photography/photo-47.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRmwAAABXRUJQVlA4IGAAAAAQAgCdASoMAAwABABoJbAAD5DvLr7HTQ/AAP7rJ1whFh743JRixS8doq5RS3rqagzpHTmk88oAyV0Kd3G/J1cBZJR1KOftZuk+6wgGahgEJXvxEwhRV/7D96yzx+rZQAA="
  },
  {
    "src": "/photography/photo-48.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAADwAQCdASoMAAwABABoJaACdADdsjXG6QAA/ugzhUng9m6LU2X4gOB7GCKSLWCp/EpTtmFHcj4l50AA"
  },
  {
    "src": "/photography/photo-49.webp",
    "width": 720,
    "height": 720,
    "blurDataURL": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAADQAQCdASoMAAwABABoJZQAAuWoMNujAAD+xKxUiEwds8lXg65qde+j4YYhqm1fX8Ln9WSEAAA="
  },
  {
    "src": "/photography/photo-50.webp",
    "width": 720,
    "height": 720,
    "blurDataURL": "data:image/webp;base64,UklGRmIAAABXRUJQVlA4IFYAAADQAQCdASoMAAwABABoJaACdACRFCOQAAD+72KTnDEvU4h+GgnehbRnLI5Tb5K+8yhIHHxrSFSC75NiHedOj0R9r6yQCaDBbW6DYOq3WyHYr+HOaAAAAA=="
  },
  {
    "src": "/photography/photo-51.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAQCdASoMAAwABABoJaQAAp3CmQO9gAD7Iu0laq4wIMEVd5EXscLojSIr5LN86/H5vKBau/DSgOkJ2SfVbrgIrqJBavO0AAA="
  },
  {
    "src": "/photography/photo-52.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADwAQCdASoMAAwABABoJbACdAEf2+N9SaAA/fyx8PWcEnHxY9pI5oXvgZ86/du10Cq62vVh3fCB0afdz/Cq1lnAWbxom7Vmcd4wjadAAAA="
  },
  {
    "src": "/photography/photo-53.webp",
    "width": 1400,
    "height": 1400,
    "blurDataURL": "data:image/webp;base64,UklGRloAAABXRUJQVlA4IE4AAADQAQCdASoMAAwABABoJaQAAqsh9zxZAAD5YIVPG0wnmOloIYiu26vJBjKTavd5lE6/IEAEuIcHwvhTufPKDfXDZdRUoqUe3wPFEGgAAAA="
  },
  {
    "src": "/photography/photo-54.webp",
    "width": 1400,
    "height": 788,
    "blurDataURL": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAAAwAgCdASoMAAcABABoJYwCdH8AGBxJ1t+AAAD+prXYjk8YG/o1FzEuuAviWYUi2poTZR+kJ41y4jMwiIknHHY4T9b1AAAA"
  }
];
